# Generated by Django 2.2 on 2019-04-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img_url',
            field=models.CharField(max_length=4096),
        ),
    ]
